#!/usr/bin/env bash
# This configures the Nginx so that its HTTP response contains a custom header (on web-01 and web-02)

sudo apt update
sudo apt install -y nginx
cd /var/www/ || exit
sudo chmod 777 html
echo 'Hello World!' > html/index.html
echo "Ceci n'est pas une page" > html/err_page.html
sudo chmod 755 html
cd /etc/nginx/ || exit
sudo chmod 777 sites-available
sudo chmod 777 sites-available/default
echo "server {
	listen 80 default_server;
	listen [::]:80 default_server;
	
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;
location / {
	
	add_header X-Served-By \"\$hostname\";
	try_files \$uri \$uri/ =404;
}
location /redirect_me{
	return 301 https://www.alxafrica.com;
}
error_page 404 /error_page.html;
location /error_page.html {
	root /var/www/html;
	internal;
}
}" > sites-available/default
sudo chmod 644 sites-available/default
sudo chmod 755 sites-available
cd ~ || exit
sudo service nginx restart
