#!/usr/bin/env bash
# This bash script has the minimum number of commands to automate the fix.
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
sed -i 's/8080/80/' /etc/nginx/sites-available/default
service nginx restart
